experiment_name: homoscedastic_gaussian
random_seed: 1998
head_type: homoscedastic_gaussian
dataset:
  type: tabular
  spec: data/length-of-stay/length_of_stay.npz
  input_dim: 35
training:
  accelerator: cpu
  batch_size: 128
  chkp_dir: chkp/length-of-stay
  chkp_freq: 15
  num_epochs: 15
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.0001
      weight_decay: 0.0001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 15
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 5
  log_dir: logs/length-of-stay
