experiment_name: test-ensemble-run
accelerator: cpu
batch_size: 32
member_head_type: gaussian
members:
  - /path/to/member.ckpt
  - /path/to/other/member.ckpt
dataset:
  type: tabular
  spec: path/to/tabular/dataset.npz
  input_dim: 1
log_dir: path/to/log/dir
