experiment_name: test-run
random_seed: 1998
head_type: double_poisson
dataset:
  type: tabular
  spec: /Users/spenceryoung/Desktop/DAI/code/deep_uncertainty/data/nonlinear_count_data/toy_data_nonlinear_count.npz
  input_dim: 1
training:
  accelerator: cpu
  batch_size: 32
  beta_scheduler:
    type: cosine_annealing
    kwargs:
      beta_0: 1.0
      beta_1: 1.0
      last_epoch: -1
  chkp_dir: /Users/spenceryoung/Desktop/DAI/code/deep_uncertainty/chkp
  chkp_freq: 20
  num_epochs: 100
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 100
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: /Users/spenceryoung/Desktop/DAI/code/deep_uncertainty/logs
