from .bible_datamodule import BibleDataModule
from .coco_people_datamodule import COCOPeopleDataModule
from .mnist_datamodule import MNISTDataModule
from .reviews_datamodule import ReviewsDataModule
from .tabular_datamodule import TabularDataModule
