dataset: mnist
lr: 1e-1
lr_min: 1e-4
lr_hyp: 0.1
lr_hyp_min: 0.1
n_epochs_burnin: 50
marglik_frequency: 25
n_hypersteps: 50
n_epochs: 500
n_epochs_val: 500
batch_size: 512
device: cuda
approx: kron
optimizer: SGD
activation: relu
model: mlp
optimizer: SGD
lr: 0.1
double: False
