width: 50
depth: 1
optimizer: Adam
lr: 1e-2
lr_min: 1e-5
n_epochs: 5000
batch_size: 256
activation: gelu
head_activation: softplus
prior_prec_init: 1.0
approx: full
device: cpu
double: True
lr_hyp: 1e-2
lr_hyp_min: 1e-3
n_epochs_burnin: 100
marglik_frequency: 50
n_hypersteps: 50