dataset:
  task: generate_linear_count_data
  x_min: 1
  x_max: 25
  n_train: 1000
  n_val: 100
  n_test: 100
  name: toy_data_nonlinear_count
  output_dir: "/Users/danielsmith/Documents/1-RL/ASU/research/DeliciousAI/code/deep_uncertainty/data/generate_linear_count_data/"
